version: '3.5'

services:

  nginx:
    image: synthetic-tablet
    container_name: synthetic-tablet
    build:
      context: .
      dockerfile: nginx/Dockerfile
    networks:
      - smart-lab
    restart: unless-stopped
    ports:
      - 8083:80

networks:
  smart-lab:
    external: true
