version: '3.5'

services:

  nginx:
    image: synthetic-tablet
    container_name: synthetic-tablet
    build:
      context: .
      dockerfile: nginx/Dockerfile
    networks:
      - reverse-proxy
    restart: unless-stopped

networks:
  reverse-proxy:
    external: true
